/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type UnifiedRiskUnits struct {
	// User ID
	UserId int64 `json:"user_id,omitempty"`
	// Spot hedging status, true - enabled, false - not enabled.
	SpotHedge bool `json:"spot_hedge,omitempty"`
	// Risk unit
	RiskUnits []RiskUnits `json:"risk_units,omitempty"`
}
