/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Current close order if any, or `null`.
type PositionCloseOrder struct {
	// Close order ID.
	Id int64 `json:"id,omitempty"`
	// Close order price.
	Price string `json:"price,omitempty"`
	// Is the close order from liquidation.
	IsLiq bool `json:"is_liq,omitempty"`
}
