/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type OptionsSettlement struct {
	// Last changed time of configuration
	Time float64 `json:"time,omitempty"`
	// Options contract name
	Contract string `json:"contract,omitempty"`
	// Settlement profit per size (quote currency)
	Profit string `json:"profit,omitempty"`
	// Settlement fee per size (quote currency)
	Fee string `json:"fee,omitempty"`
	// Strike price (quote currency)
	StrikePrice string `json:"strike_price,omitempty"`
	// Settlement price (quote currency)
	SettlePrice string `json:"settle_price,omitempty"`
}
