/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Retrieve risk limit configurations for different tiers under a specified contract.
type FuturesLimitRiskTiers struct {
	// Tier
	Tier int32 `json:"tier,omitempty"`
	// Position risk limit
	RiskLimit string `json:"risk_limit,omitempty"`
	// Initial margin rate
	InitialRate string `json:"initial_rate,omitempty"`
	// Maintenance margin rate
	MaintenanceRate string `json:"maintenance_rate,omitempty"`
	// Maximum leverage
	LeverageMax string `json:"leverage_max,omitempty"`
	// Markets, visible only during market pagination requests
	Contract string `json:"contract,omitempty"`
	// Maintenance margin quick calculation deduction
	Deduction string `json:"deduction,omitempty"`
}
