/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Market gradient information.
type MarginLeverageTier struct {
	// Maximum loan limit.
	UpperLimit string `json:"upper_limit,omitempty"`
	// Maintenance margin rate.
	Mmr string `json:"mmr,omitempty"`
	// Maximum leverage multiple.
	Leverage string `json:"leverage,omitempty"`
}
