/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Dual Investment order
type PlaceDualInvestmentOrder struct {
	// Plan ID
	PlanId string `json:"plan_id"`
	// The number of copies is mutually exclusive with the amount field and will be deprecated soon. It is recommended to use the amount parameter.
	Copies string `json:"copies,omitempty"`
	// Whether to purchase at the maximum. Mutually exclusive with the amount field. Will be deprecated soon. It is recommended to use the amount parameter.
	IsMax int32 `json:"is_max,omitempty"`
	// Subscription amount, mutually exclusive with the copies field
	Amount string `json:"amount"`
	// User defined information. If not empty, must follow the rules below:  1. prefixed with `t-` 2. no longer than 28 bytes without `t-` prefix 3. can only include 0-9, A-Z, a-z, underscore(_), hyphen(-) or dot(.)
	Text string `json:"text,omitempty"`
}
