/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CollateralCurrencyRes struct {
	// Update success status
	Succeeded bool `json:"succeeded,omitempty"`
	// Error identifier for unsuccessful operations; empty for successful.
	Label string `json:"label,omitempty"`
	// Error description in case of operation failure; empty when successful.
	Message string `json:"message,omitempty"`
	// Currency
	Currency string `json:"currency,omitempty"`
	// Quantity of successful collateral operation; 0 if the operation fails.
	Amount string `json:"amount,omitempty"`
}
