/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type SpotAccount struct {
	// Currency detail
	Currency string `json:"currency,omitempty"`
	// Available amount
	Available string `json:"available,omitempty"`
	// Locked amount, used in trading
	Locked string `json:"locked,omitempty"`
}
