/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type MultiChainAddressItem struct {
	// Name of the chain
	Chain string `json:"chain,omitempty"`
	// Deposit address
	Address string `json:"address,omitempty"`
	// Notes that some currencies required(e.g., Tag, Memo) when depositing
	PaymentId string `json:"payment_id,omitempty"`
	// Note type, `Tag` or `Memo`
	PaymentName string `json:"payment_name,omitempty"`
	// The obtain failed status- 0: address successfully obtained- 1: failed to obtain address
	ObtainFailed int32 `json:"obtain_failed,omitempty"`
}
