/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Futures order
type MockFuturesOrder struct {
	// Futures name, currently only supports perpetual futures for BTC and ETH with USDT.
	Contract string `json:"contract"`
	// Futures quantity, representing the initial order quantity, not involved in actual settlement.
	Size string `json:"size"`
	// Unfilled contract quantity, involved in actual calculation
	Left string `json:"left"`
}
