/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Futures position details
type OptionsPosition struct {
	// User ID
	User int32 `json:"user,omitempty"`
	// Futures contract
	Contract string `json:"contract,omitempty"`
	// Position size
	Size int64 `json:"size,omitempty"`
	// Entry price
	EntryPrice string `json:"entry_price,omitempty"`
	// Current mark price
	MarkPrice string `json:"mark_price,omitempty"`
	// Realized PNL
	RealisedPnl string `json:"realised_pnl,omitempty"`
	// Unrealized PNL
	UnrealisedPnl string `json:"unrealised_pnl,omitempty"`
	// Current open orders
	PendingOrders int32               `json:"pending_orders,omitempty"`
	CloseOrder    *PositionCloseOrder `json:"close_order,omitempty"`
}
