/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Interest Record.
type UniInterestRecord struct {
	// Status: 0 - fail, 1 - success.
	Status int32 `json:"status,omitempty"`
	// Currency.
	Currency string `json:"currency,omitempty"`
	// Actual Rate.
	ActualRate string `json:"actual_rate,omitempty"`
	// Interest.
	Interest string `json:"interest,omitempty"`
	// Interest status: interest_dividend - Normal dividend, interest_reinvest - Interest reinvestment
	InterestStatus string `json:"interest_status,omitempty"`
	// Created time.
	CreateTime int64 `json:"create_time,omitempty"`
}
