/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type SpotInsuranceHistory struct {
	// Currency
	Currency string `json:"currency,omitempty"`
	// 余额
	Balance string `json:"balance,omitempty"`
	// Creation time, timestamp, milliseconds
	Time int64 `json:"time,omitempty"`
}
