/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// 统一账户抵押模式设置返回
type UnifiedCollateralRes struct {
	// 是否设置成功
	IsSuccess bool `json:"is_success,omitempty"`
}
