/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Initiate a flash swap order preview
type FlashSwapOrderPreview struct {
	// Preview result ID
	PreviewId string `json:"preview_id,omitempty"`
	// Currency to sell which can be retrieved from supported currency list API `GET /flash_swap/currencies`
	SellCurrency string `json:"sell_currency,omitempty"`
	// Amount to sell
	SellAmount string `json:"sell_amount,omitempty"`
	// Currency to buy which can be retrieved from supported currency list API `GET /flash_swap/currencies`
	BuyCurrency string `json:"buy_currency,omitempty"`
	// Amount to buy
	BuyAmount string `json:"buy_amount,omitempty"`
	// Price
	Price string `json:"price,omitempty"`
}
