/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Repay Multi-Collateral Loan
type MultiRepayResp struct {
	// Order ID
	OrderId int64 `json:"order_id,omitempty"`
	// Repay Currency List
	RepaidCurrencies []RepayCurrencyRes `json:"repaid_currencies,omitempty"`
}
