/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type MultiCollateralRecordCurrency struct {
	// Currency.
	Currency string `json:"currency,omitempty"`
	// Currency Index Price.
	IndexPrice string `json:"index_price,omitempty"`
	// Amount before the operation.
	BeforeAmount string `json:"before_amount,omitempty"`
	// USDT Amount before the operation.
	BeforeAmountUsdt string `json:"before_amount_usdt,omitempty"`
	// Amount after the operation.
	AfterAmount string `json:"after_amount,omitempty"`
	// USDT Amount after the operation.
	AfterAmountUsdt string `json:"after_amount_usdt,omitempty"`
}
