/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type UnifiedCollateralReq struct {
	// 用户设置抵押物模式 0(all)-全部币种作为抵押物,1(custom)-自定义币种作为抵押物,collateral_type为0(all)时，enable_list与disable_list参数无效
	CollateralType int32 `json:"collateral_type,omitempty"`
	// 币种列表，collateral_type=1(custom)表示追加的逻辑
	EnableList []string `json:"enable_list,omitempty"`
	// 取消列表，表示取消的逻辑
	DisableList []string `json:"disable_list,omitempty"`
}
