/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type LedgerRecord struct {
	// Record ID
	Id string `json:"id,omitempty"`
	// Hash record of the withdrawal
	Txid string `json:"txid,omitempty"`
	// Operation time
	Timestamp string `json:"timestamp,omitempty"`
	// Currency amount
	Amount string `json:"amount"`
	// Currency name
	Currency string `json:"currency"`
	// Withdrawal address. Required for withdrawals
	Address string `json:"address,omitempty"`
	// Additional remarks with regards to the withdrawal
	Memo string `json:"memo,omitempty"`
	// Record status.  - DONE: done - CANCEL: cancelled - REQUEST: requesting - MANUAL: pending manual approval - BCODE: GateCode operation - EXTPEND: pending confirm after sending - FAIL: pending confirm when fail
	Status string `json:"status,omitempty"`
	// Name of the chain used in withdrawals
	Chain string `json:"chain,omitempty"`
}
