/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Lend or redeem
type CreateUniLend struct {
	// Currency name
	Currency string `json:"currency"`
	// The amount of currency could be lent
	Amount string `json:"amount"`
	// type: lend - lend, redeem - redeem
	Type string `json:"type"`
	// The minimum interest rate. If the value is too high, it might lead to the unsuccessful lending and no profit will be gained for that hour.
	MinRate string `json:"min_rate,omitempty"`
}
