/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type FuturesLiqOrder struct {
	// Liquidation time
	Time int64 `json:"time,omitempty"`
	// Futures contract
	Contract string `json:"contract,omitempty"`
	// User position size
	Size int64 `json:"size,omitempty"`
	// Liquidation order price
	OrderPrice string `json:"order_price,omitempty"`
	// Liquidation order average taker price
	FillPrice string `json:"fill_price,omitempty"`
	// System liquidation order maker size
	Left int64 `json:"left,omitempty"`
}
