/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CrossMarginLoan struct {
	// Borrow loan ID
	Id string `json:"id,omitempty"`
	// Creation timestamp, in milliseconds
	CreateTime int64 `json:"create_time,omitempty"`
	// Update timestamp, in milliseconds
	UpdateTime int64 `json:"update_time,omitempty"`
	// Currency name
	Currency string `json:"currency"`
	// Borrowed amount
	Amount string `json:"amount"`
	// User defined custom ID
	Text string `json:"text,omitempty"`
	// Borrow loan status, which includes:  - 1: failed to borrow - 2: borrowed but not repaid - 3: repayment complete
	Status int32 `json:"status,omitempty"`
	// Repaid amount
	Repaid string `json:"repaid,omitempty"`
	// Repaid interest
	RepaidInterest string `json:"repaid_interest,omitempty"`
	// Outstanding interest yet to be paid
	UnpaidInterest string `json:"unpaid_interest,omitempty"`
}
