/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type SavedAddress struct {
	// Currency
	Currency string `json:"currency,omitempty"`
	// Chain name
	Chain string `json:"chain,omitempty"`
	// Address
	Address string `json:"address,omitempty"`
	// Name
	Name string `json:"name,omitempty"`
	// Tag
	Tag string `json:"tag,omitempty"`
	// Whether to pass the verification 0-unverified, 1-verified
	Verified string `json:"verified,omitempty"`
}
