/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type MyFuturesTrade struct {
	// Trade ID
	Id int64 `json:"id,omitempty"`
	// Trading time
	CreateTime float64 `json:"create_time,omitempty"`
	// Futures contract
	Contract string `json:"contract,omitempty"`
	// Order ID related
	OrderId string `json:"order_id,omitempty"`
	// Trading size
	Size int64 `json:"size,omitempty"`
	// Number of closed positions:  close_size=0 && size＞0       Open long position close_size=0 && size＜0       Open short position close_size>0 && size>0 && size <= close_size Close short postion close_size>0 && size>0 && size > close_size Close short position and open long position close_size<0 && size<0 && size >= close_size Close long postion close_size<0 && size<0 && size < close_size Close long position and open short position
	CloseSize int64 `json:"close_size,omitempty"`
	// Trading price
	Price string `json:"price,omitempty"`
	// Trade role. Available values are `taker` and `maker`
	Role string `json:"role,omitempty"`
	// User defined information
	Text string `json:"text,omitempty"`
	// Fee deducted
	Fee string `json:"fee,omitempty"`
	// Points used to deduct fee
	PointFee string `json:"point_fee,omitempty"`
}
