/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Margin account detail. `base` refers to base currency, while `quotes to quote currency
type MarginAccount struct {
	// Currency pair
	CurrencyPair string `json:"currency_pair,omitempty"`
	// Whether account is locked
	Locked bool `json:"locked,omitempty"`
	// Current risk rate of margin account
	Risk  string                `json:"risk,omitempty"`
	Base  MarginAccountCurrency `json:"base,omitempty"`
	Quote MarginAccountCurrency `json:"quote,omitempty"`
}
