/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type Ticker struct {
	// Currency pair.
	CurrencyPair string `json:"currency_pair,omitempty"`
	// Last trading price.
	Last string `json:"last,omitempty"`
	// Recent lowest ask.
	LowestAsk string `json:"lowest_ask,omitempty"`
	// The latest seller's lowest price quantity; does not exist for batch query; exists for single query, and is empty if there is no data
	LowestSize string `json:"lowest_size,omitempty"`
	// Recent highest bid.
	HighestBid string `json:"highest_bid,omitempty"`
	// The latest buyer's highest price quantity; does not exist for batch query; exists for single query, and is empty if there is no data
	HighestSize string `json:"highest_size,omitempty"`
	// Change percentage in the last 24h.
	ChangePercentage string `json:"change_percentage,omitempty"`
	// utc0 timezone, the percentage change in the last 24 hours.
	ChangeUtc0 string `json:"change_utc0,omitempty"`
	// utc8 timezone, the percentage change in the last 24 hours.
	ChangeUtc8 string `json:"change_utc8,omitempty"`
	// Base currency trade volume in the last 24h.
	BaseVolume string `json:"base_volume,omitempty"`
	// Quote currency trade volume in the last 24h.
	QuoteVolume string `json:"quote_volume,omitempty"`
	// Highest price in 24h.
	High24h string `json:"high_24h,omitempty"`
	// Lowest price in 24h.
	Low24h string `json:"low_24h,omitempty"`
	// ETF net value.
	EtfNetValue string `json:"etf_net_value,omitempty"`
	// ETF previous net value at re-balancing time.
	EtfPreNetValue *string `json:"etf_pre_net_value,omitempty"`
	// ETF previous re-balancing time.
	EtfPreTimestamp *int64 `json:"etf_pre_timestamp,omitempty"`
	// ETF current leverage.
	EtfLeverage *string `json:"etf_leverage,omitempty"`
}
