/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type UnifiedLeverageConfig struct {
	// Current leverage ratio.
	CurrentLeverage string `json:"current_leverage,omitempty"`
	// Minimum adjustable leverage ratio.
	MinLeverage string `json:"min_leverage,omitempty"`
	// Maximum adjustable leverage ratio.
	MaxLeverage string `json:"max_leverage,omitempty"`
	// Current liabilities.
	Debit string `json:"debit,omitempty"`
	// Available Margin.
	AvailableMargin string `json:"available_margin,omitempty"`
	// The current leverage you can choose is.
	Borrowable string `json:"borrowable,omitempty"`
	// The maximum amount of margin that can be borrowed and the be borrowed, whichever is smaller
	ExceptLeverageBorrowable string `json:"except_leverage_borrowable,omitempty"`
}
