/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CrossMarginRepayment struct {
	// Loan record ID
	Id string `json:"id,omitempty"`
	// Repayment time
	CreateTime int64 `json:"create_time,omitempty"`
	// Loan record ID
	LoanId string `json:"loan_id,omitempty"`
	// Currency name
	Currency string `json:"currency,omitempty"`
	// Repaid principal
	Principal string `json:"principal,omitempty"`
	// Repaid interest
	Interest string `json:"interest,omitempty"`
	// Repayment type: none - no repayment type, manual_repay - manual repayment, auto_repay - automatic repayment, cancel_auto_repay - automatic repayment after cancellation
	RepaymentType string `json:"repayment_type,omitempty"`
}
