/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Repay
type RepayLoan struct {
	// Order ID
	OrderId int64 `json:"order_id"`
	// Repayment amount, it is mandatory when making partial repayments
	RepayAmount string `json:"repay_amount"`
	// Repayment method, set to `true` for full repayment, and `false` for partial repayment; When set to false for partial repayment, the repay_amount parameter cannot be greater than the remaining amount to be repaid by the user.
	RepaidAll bool `json:"repaid_all"`
}
