/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type FuturesOrderBook struct {
	// Order Book ID. Increases by 1 on every order book change. Set `with_id=true` to include this field in response
	Id int64 `json:"id,omitempty"`
	// Response data generation timestamp
	Current float64 `json:"current,omitempty"`
	// Order book changed timestamp
	Update float64 `json:"update,omitempty"`
	// Asks order depth
	Asks []FuturesOrderBookItem `json:"asks"`
	// Bids order depth
	Bids []FuturesOrderBookItem `json:"bids"`
}
