/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type DualGetOrders struct {
	// Order ID
	Id int32 `json:"id,omitempty"`
	// Plan ID
	PlanId int32 `json:"plan_id,omitempty"`
	// Copies
	Copies string `json:"copies,omitempty"`
	// Investment Amount
	InvestAmount string `json:"invest_amount,omitempty"`
	// Settlement Amount
	SettlementAmount string `json:"settlement_amount,omitempty"`
	// Creation time
	CreateTime int32 `json:"create_time,omitempty"`
	// Completion Time
	CompleteTime int32 `json:"complete_time,omitempty"`
	// Status:  `INIT`-INIT `SETTLEMENT_SUCCESS`-Settlement Success `SETTLEMENT_PROCESSING`-SEttlement Processing `CANCELED`-Canceled `FAILED`-Failed
	Status string `json:"status,omitempty"`
	// Investment Currency
	InvestCurrency string `json:"invest_currency,omitempty"`
	// Strike Currency
	ExerciseCurrency string `json:"exercise_currency,omitempty"`
	// Strike price
	ExercisePrice string `json:"exercise_price,omitempty"`
	// settlement price
	SettlementPrice string `json:"settlement_price,omitempty"`
	// Settle currency
	SettlementCurrency string `json:"settlement_currency,omitempty"`
	// APY
	ApyDisplay string `json:"apy_display,omitempty"`
	// Settlement APY
	ApySettlement string `json:"apy_settlement,omitempty"`
	// Settlement time
	DeliveryTime int32 `json:"delivery_time,omitempty"`
	// Custom order information
	Text string `json:"text,omitempty"`
}
