/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// The output of the portfolio margin calculator.
type UnifiedPortfolioOutput struct {
	// Total maintenance margin, including only the portfolio margin calculation results for positions in the risk unit,  excluding borrowed margin. If borrowing exists, conventional borrowing margin requirements will still apply.
	MaintainMarginTotal string `json:"maintain_margin_total,omitempty"`
	// Total initial margin, calculated as the maximum of the following three combinations: position,  position + positive delta orders, position + negative delta orders.
	InitialMarginTotal string `json:"initial_margin_total,omitempty"`
	// Calculate time
	CalculateTime int64 `json:"calculate_time,omitempty"`
	// Risk unit
	RiskUnit []MockRiskUnit `json:"risk_unit,omitempty"`
}
