/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Unified margin tiers.
type UnifiedMarginTiers struct {
	// Currency name.
	Currency string `json:"currency,omitempty"`
	// Margin tiers.
	MarginTiers []MarginTiers `json:"margin_tiers,omitempty"`
}
