/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type UnifiedCurrency struct {
	// Currency name
	Name string `json:"name,omitempty"`
	// Currency precision
	Prec string `json:"prec,omitempty"`
	// The minimum debit limit is the unit of currency
	MinBorrowAmount string `json:"min_borrow_amount,omitempty"`
	// The minimum debit limit is the unit of currency
	UserMaxBorrowAmount string `json:"user_max_borrow_amount,omitempty"`
	// The maximum debit limit for the platform is USDT
	TotalMaxBorrowAmount string `json:"total_max_borrow_amount,omitempty"`
	// Does the lending status  - `disable` : Loans are prohibited  - `enable`: Support lending
	LoanStatus string `json:"loan_status,omitempty"`
}
