/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Options underlying detail
type OptionsUnderlyingTicker struct {
	// Total put options trades amount in last 24h
	TradePut int64 `json:"trade_put,omitempty"`
	// Total call options trades amount in last 24h
	TradeCall int64 `json:"trade_call,omitempty"`
	// Index price
	IndexPrice string `json:"index_price,omitempty"`
}
