/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Spot order details
type OrderPatch struct {
	// New order amount. `amount` and `price` must specify one of them
	Amount string `json:"amount,omitempty"`
	// New order price. `amount` and `Price` must specify one of them\"
	Price string `json:"price,omitempty"`
}
