/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type MarginAccountBook struct {
	// Balance change record ID
	Id string `json:"id,omitempty"`
	// Balance changed timestamp
	Time string `json:"time,omitempty"`
	// The timestamp of the change (in milliseconds)
	TimeMs int64 `json:"time_ms,omitempty"`
	// Currency changed
	Currency string `json:"currency,omitempty"`
	// Account currency pair
	CurrencyPair string `json:"currency_pair,omitempty"`
	// Amount changed. Positive value means transferring in, while negative out
	Change string `json:"change,omitempty"`
	// Balance after change
	Balance string `json:"balance,omitempty"`
}
