/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Collateral Ratio.
type CollateralLtv struct {
	// The initial collateralization rate.
	InitLtv string `json:"init_ltv,omitempty"`
	// Warning collateralization ratio.
	AlertLtv string `json:"alert_ltv,omitempty"`
	// The liquidation collateralization rate.
	LiquidateLtv string `json:"liquidate_ltv,omitempty"`
}
