/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type SpotAccountBook struct {
	// Balance change record ID
	Id string `json:"id,omitempty"`
	// The timestamp of the change (in milliseconds)
	Time int64 `json:"time,omitempty"`
	// Currency changed
	Currency string `json:"currency,omitempty"`
	// Amount changed. Positive value means transferring in, while negative out
	Change string `json:"change,omitempty"`
	// Balance after change
	Balance string `json:"balance,omitempty"`
	// Account book type.  Please refer to [account book type](#accountbook-type) for more detail
	Type string `json:"type,omitempty"`
	// Additional information
	Text string `json:"text,omitempty"`
}
