/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type SpotPriceTrigger struct {
	// Trigger price
	Price string `json:"price"`
	// Price trigger condition  - `>=`: triggered when market price larger than or equal to `price` field - `<=`: triggered when market price less than or equal to `price` field
	Rule string `json:"rule"`
	// How long (in seconds) to wait for the condition to be triggered before cancelling the order.
	Expiration int32 `json:"expiration"`
}
