/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type FuturesAutoDeleverage struct {
	// Automatic deleveraging time
	Time int64 `json:"time,omitempty"`
	// User ID
	User int64 `json:"user,omitempty"`
	// Order ID. Order IDs before 2023-02-20 are null
	OrderId int64 `json:"order_id,omitempty"`
	// Futures contract
	Contract string `json:"contract,omitempty"`
	// Position leverage
	Leverage string `json:"leverage,omitempty"`
	// Cross margin leverage(valid only when `leverage` is 0)
	CrossLeverageLimit string `json:"cross_leverage_limit,omitempty"`
	// Average entry price
	EntryPrice string `json:"entry_price,omitempty"`
	// Average fill price
	FillPrice string `json:"fill_price,omitempty"`
	// Trading size
	TradeSize int64 `json:"trade_size,omitempty"`
	// Positions after auto-deleveraging
	PositionSize int64 `json:"position_size,omitempty"`
}
