/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Info of order to be cancelled
type CancelBatchOrder struct {
	// Order currency pair
	CurrencyPair string `json:"currency_pair"`
	// Order ID or user custom ID. Custom ID are accepted only within 30 minutes after order creation
	Id string `json:"id"`
	// Processing Mode: When placing an order, different fields are returned based on action_mode. This field is only valid during the request and is not included in the response result ACK: Asynchronous mode, only returns key order fields RESULT: No clearing information FULL: Full mode (default)
	ActionMode string `json:"action_mode,omitempty"`
}
