/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type MultiLoanRepayItem struct {
	// Repayment currency
	Currency string `json:"currency,omitempty"`
	// Size
	Amount string `json:"amount,omitempty"`
	// Repayment method, set to true for full repayment, false for partial repayment.
	RepaidAll bool `json:"repaid_all,omitempty"`
}
