/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type UnifiedSettings struct {
	// USDT contract switch. In cross-currency margin mode, it can only be turned on and not off
	UsdtFutures bool `json:"usdt_futures,omitempty"`
	// Spot hedging switch.
	SpotHedge bool `json:"spot_hedge,omitempty"`
	// switch, when the mode is cross-currency margin mode, whether to use Uniloan financial funds as margin
	UseFunding bool `json:"use_funding,omitempty"`
	// Option switch. In cross-currency margin mode, it can only be turned on and not off
	Options bool `json:"options,omitempty"`
}
