/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type BorrowCurrencyInfo struct {
	// Currency
	Currency string `json:"currency,omitempty"`
	// Currency Index Price
	IndexPrice string `json:"index_price,omitempty"`
	// outstanding principal
	LeftRepayPrincipal string `json:"left_repay_principal,omitempty"`
	// outstanding interest
	LeftRepayInterest string `json:"left_repay_interest,omitempty"`
	// Value of left total repayments amount in USDT
	LeftRepayUsdt string `json:"left_repay_usdt,omitempty"`
}
