/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type SwapCoinStruct struct {
	// Order ID
	Id int32 `json:"id,omitempty"`
	// User ID
	Uid int32 `json:"uid,omitempty"`
	// Currency
	Coin string `json:"coin,omitempty"`
	// Type: 0-Lock, 1-Certificate
	Type int32 `json:"type,omitempty"`
	// Amount
	Amount string `json:"amount,omitempty"`
	// Exchange Ratio
	ExchangeRate string `json:"exchange_rate,omitempty"`
	// Plan ID
	Pid int32 `json:"pid,omitempty"`
	// status 1-success
	Status int32 `json:"status,omitempty"`
	// Transaction timestamp
	CreateStamp int32 `json:"createStamp,omitempty"`
}
