/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type OpenOrders struct {
	// Currency pair.
	CurrencyPair string `json:"currency_pair,omitempty"`
	// The total number of pending orders for this trading pair on the current page
	Total  int32   `json:"total,omitempty"`
	Orders []Order `json:"orders,omitempty"`
}
