/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Interest Record
type UniLendRecord struct {
	// Currency name
	Currency string `json:"currency,omitempty"`
	// current amount
	Amount string `json:"amount,omitempty"`
	// Last wallet amount
	LastWalletAmount string `json:"last_wallet_amount,omitempty"`
	// Last lent amount
	LastLentAmount string `json:"last_lent_amount,omitempty"`
	// Last frozen amount
	LastFrozenAmount string `json:"last_frozen_amount,omitempty"`
	// Record type: lend - lend, redeem - redeem
	Type string `json:"type,omitempty"`
	// Created time
	CreateTime int64 `json:"create_time,omitempty"`
}
