/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Multi-collateral fixed interest rate
type CollateralFixRate struct {
	// Currency
	Currency string `json:"currency,omitempty"`
	// Fixed interest rate for a lending period of 7 days
	Rate7d string `json:"rate_7d,omitempty"`
	// Fixed interest rate for a lending period of 30 days
	Rate30d string `json:"rate_30d,omitempty"`
	// Update time, timestamp, unit in seconds
	UpdateTime int64 `json:"update_time,omitempty"`
}
