/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type OptionsAccountBook struct {
	// Change time
	Time float64 `json:"time,omitempty"`
	// Amount changed (USDT)
	Change string `json:"change,omitempty"`
	// Account total balance after change (USDT)
	Balance string `json:"balance,omitempty"`
	// Changing Type: - dnw: Deposit & Withdraw - prem: Trading premium - fee: Trading fee - refr: Referrer rebate - point_dnw: POINT Deposit & Withdraw - point_fee: POINT Trading fee - point_refr: POINT Referrer rebate
	Type string `json:"type,omitempty"`
	// custom text
	Text string `json:"text,omitempty"`
}
