/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type AgencyCommission struct {
	// Commission Time. (unix timestamp)
	CommissionTime int64 `json:"commission_time,omitempty"`
	// User ID
	UserId int64 `json:"user_id,omitempty"`
	// Group name
	GroupName string `json:"group_name,omitempty"`
	// Commission Amount
	CommissionAmount string `json:"commission_amount,omitempty"`
	// Commission Asset
	CommissionAsset string `json:"commission_asset,omitempty"`
	// Source.  SPOT - SPOT Rebate, FUTURES - Futures Rebate
	Source string `json:"source,omitempty"`
}
