/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// data point in every timestamp
type FuturesPremiumIndex struct {
	// Unix timestamp in seconds
	T float64 `json:"t,omitempty"`
	// Close price
	C string `json:"c,omitempty"`
	// Highest price
	H string `json:"h,omitempty"`
	// Lowest price`
	L string `json:"l,omitempty"`
	// Open price
	O string `json:"o,omitempty"`
}
