/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CrossMarginRepayment struct {
	// Loan record ID
	Id string `json:"id,omitempty"`
	// Repayment time
	CreateTime int64 `json:"create_time,omitempty"`
	// Borrow loan ID
	LoanId string `json:"loan_id,omitempty"`
	// Currency name
	Currency string `json:"currency,omitempty"`
	// Repaid principal
	Principal string `json:"principal,omitempty"`
	// Repaid interest
	Interest string `json:"interest,omitempty"`
}
