/*
 * Gate API
 *
 * Welcome to Gate API  APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Countdown cancel task detail.
type CountdownCancelAllFuturesTask struct {
	// Countdown time in seconds At least 5 seconds, 0 means cancel countdown
	Timeout int32 `json:"timeout"`
	// Futures contract.
	Contract string `json:"contract,omitempty"`
}
