/*
 * Gate API v4
 *
 * Welcome to Gate API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Quotation Response
type QuoteResponse struct {
	// The quotation ID (quote_id) is used for placing orders and is valid for 1 minute
	QuoteId string `json:"quote_id,omitempty"`
	// 最小下单量
	MinAmount string `json:"min_amount,omitempty"`
	// 最大下单量
	MaxAmount string `json:"max_amount,omitempty"`
	// Coin Price (USDT-based)
	Price string `json:"price,omitempty"`
	// Slippage
	Slippage string `json:"slippage,omitempty"`
	// Estimated Network Fee (USDT-based)
	EstimateGasFeeAmountUsdt string `json:"estimate_gas_fee_amount_usdt,omitempty"`
	// Slippage value of 10 represents a 10% tolerance
	OrderFee string `json:"order_fee,omitempty"`
	// 最小获得数量
	TargetTokenMinAmount string `json:"target_token_min_amount,omitempty"`
	// 最大获得数量
	TargetTokenMaxAmount string `json:"target_token_max_amount,omitempty"`
	// Failure Type - `0` : Success - `1` : Exceeds maximum value - `2` : Below minimum value
	ErrorType int32 `json:"error_type,omitempty"`
}
