/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type SubAccountToSubAccount struct {
	// Transfer currency name
	Currency string `json:"currency"`
	// Transfer from the account. (deprecate, use `sub_account_from_type` and `sub_account_to_type` instead)
	SubAccountType string `json:"sub_account_type,omitempty"`
	// Transfer from the user id of the sub-account
	SubAccountFrom string `json:"sub_account_from"`
	// Transfer from the account.  `spot` - spot account, `futures` - perpetual contract account, `cross_margin` - cross margin account
	SubAccountFromType string `json:"sub_account_from_type"`
	// Transfer to the user id of the sub-account
	SubAccountTo string `json:"sub_account_to"`
	// Transfer to the account.  `spot` - spot account, `futures` - perpetual contract account, `cross_margin` - cross margin account
	SubAccountToType string `json:"sub_account_to_type"`
	// Transfer amount
	Amount string `json:"amount"`
}
