/*
 * Gate API v4
 *
 * Welcome to Gate.io API  APIv4 provides spot, margin and futures trading operations. There are public APIs to retrieve the real-time market statistics, and private APIs which needs authentication to trade on user's behalf.
 *
 * Contact: support@mail.gate.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// MMP Reset
type OptionsMmpReset struct {
	// Underlying
	Underlying string `json:"underlying"`
	// Time window (milliseconds), between 1-5000, 0 means disabling MMP
	Window int32 `json:"window,omitempty"`
	// Freeze duration (milliseconds), 0 means always frozen, need to call reset API to unfreeze
	FrozenPeriod int32 `json:"frozen_period,omitempty"`
	// Trading volume upper limit (positive number, up to 2 decimal places)
	QtyLimit string `json:"qty_limit,omitempty"`
	// Upper limit of net delta value (positive number, up to 2 decimal places)
	DeltaLimit string `json:"delta_limit,omitempty"`
	// Trigger freeze time (milliseconds), 0 means no freeze is triggered
	TriggerTimeMs int64 `json:"trigger_time_ms,omitempty"`
	// Unfreeze time (milliseconds). If the freeze duration is not configured, there will be no unfreeze time after the freeze is triggered.
	FrozenUntilMs int64 `json:"frozen_until_ms,omitempty"`
}
